version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: yeoman-test
    versions:
    - 4.0.0
- package-ecosystem: npm
  directory: "/generators/app/templates/base"
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
